title: Final Capstone Project - CS-499
description: Welcome to my Final Capstone Project for CS-499. This repository contains all the necessary artifacts and documentation.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
